### ISSUE TITLE
duration is in milliseconds

### ISSUE THREAD

**Issue by juckerf** [idealley/feathers-hooks-rediscache#11]
moments js duration() is per default in milliseconds.
Proposed change: https://github.com/juckerf/feathers-hooks-rediscache/commit/02fc95a748f6b41f93962d4af70870c4966a839c
(unfortunately I'm not able to create a PR right now, because some other changes in my fork will probably break the code)

**Comment by juckerf** [comment]
(and this one https://github.com/juckerf/feathers-hooks-rediscache/commit/4d896948f5d3b6d3491f887c06b81754f26015ea)

**Comment by idealley** [comment]
Thank you
