### ISSUE TITLE
Cache key error

### ISSUE THREAD

**Issue by sajov** [idealley/feathers-hooks-rediscache#14]
"products?id[$nin]=1" end up in "products?id="

**Comment by idealley** [comment]
Weird I will check that.

**Comment by idealley** [comment]
I have identified the problem. I did not know you could pass such params, very interesting. I will fix this ASAP.

**Comment by idealley** [comment]
Thank you for reporting the bug. it is now fixed. Let me know if you have any other issue.

**Comment by sajov** [comment]
Many thanks!
