### ISSUE TITLE
Nested route with optional params not being indexed properly

### ISSUE THREAD

**Issue by oppodeldoc** [idealley/feathers-hooks-rediscache#17]
Hi there!  Thanks for this great project, we're really hoping we can use it as it fits our needs perfectly at the moment, but we've found a weird issue that I'm hoping has an easy solution.

### Steps to reproduce
1. Create a service in Feathers with a route like `/posts/:site?`, this is i.e. to handle posts across several sites that may have identical IDs, slugs, etc. So a `posts.service.js` would have this line:
```js
// Initialize our service with any options it requires
app.use('/posts/:something?', createService(options)) 
```
2. Configure this project as per the docs. 
3. Start up the service and go to http://localhost:3030/posts/foo
4. Check out http://localhost:3030/cache/index to see how things are indexed

### Expected behavior
I'd expect to see a response like:
```json
[
    "group-foo",
    "posts/foo"
]
```

### Actual behavior
Instead I see:
```json
[
    "group-posts/:something?",
    "posts/:something?"
]
```
This means that any of our other site routes (`posts/bar`, `posts/baz`) will all be cached under the same key. Nested routes like `posts/foo/1234` are indexed as:
```json
[
    "group-posts/:something?",
    "posts/:something?/1234"
]
```
So nested routes are working, it's just that the dynamic part of the route seems to be broken.

### System configuration
Here's the `config/default.json` file:
```json
{
  "host": "localhost",
  "port": 3030,
  "public": "../public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "redisCache" : {
    "defaultDuration": 60,
    "parseNestedRoutes": true,
    "removePathFromCacheKey": false
  },
  "redis" : {
    "host": "localhost",
    "port": 6379
  }
}
```
I'm running the latest version of your repo `0.3.4`

I'm happy to submit a PR, but not quite sure where to look. Can you shed some light as to why the dynamic routes aren't being handled?  Thanks again!

**Comment by oppodeldoc** [comment]
@idealley I've narrowed this down to a simple tweak to the RegEx in the path parsing helper. PR forthcoming!

**Comment by oppodeldoc** [comment]
@idealley Thanks for the quick merge!  Unfortunately, it looks like the NPM package is a little weird. The change is showing up in the minified version `library.min.js` but not in `library.js` and the `package.json` is pointing at the unminified version. Can you update when you have the chance? Thanks again!

**Comment by idealley** [comment]
Doing now

**Comment by idealley** [comment]
That should be ok now.  I have patched it, and published. I have also tested it in my project and it works. Thank you for noticing and sorry for the trouble.

Sam

**Comment by oppodeldoc** [comment]
Works great now, thanks so much!
