### ISSUE TITLE
Route Subfolders break cache clearing

### ISSUE THREAD

**Issue by jamesvillarrubia** [idealley/feathers-hooks-rediscache#54]
### Steps to reproduce

Setup cache on a nested route with a version number ahead of the service.  Example: 
example.com/v1/resources/1?test=true

To clear the cache, I'm running GET cache/clear/single/v1/resources/1?test=true

### Expected behavior

Cache key should be 'v1/resources/1?test=true'

### Actual behavior
Error.  Cannot find path.

### Proposed Solution (What worked for me)
```
 router.get('/clear/single/:target', (req, res) => {
    let target = decodeURIComponent(req.params.target);
```
becomes
```
  router.get('/clear/single/*', (req, res) => {
    let target = decodeURIComponent(req.params[0]); 
```

If this sounds like a useful tweak, I'm happy to submit a PR.

**Comment by idealley** [comment]
Hello, Thank you for reporting.

Glad to accept a PR!

**Comment by idealley** [comment]
Thank you!
